[project]
name = "second-brain-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.12",
    "pydantic>=2.11.3",
    "pydantic-ai>=0.1.3",
    "toml>=0.10.2",
    "uvicorn>=0.34.2",
]
